# Generated by Django 5.1.15 on 2026-07-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Cloudinary URL for the collection image.",
                        max_length=500,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active collections are shown on the storefront.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("meta_title", models.CharField(blank=True, default="", max_length=160)),
                ("meta_description", models.TextField(blank=True, default="", max_length=320)),
            ],
            options={
                "verbose_name": "collection",
                "verbose_name_plural": "collections",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
