# Generated by Django 5.1.15 on 2026-07-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnnouncementBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=300)),
                ("link_url", models.URLField(blank=True, default="", max_length=500)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "announcement",
                "verbose_name_plural": "announcements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HeroBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, default="", max_length=300)),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Cloudinary URL for the banner image.",
                        max_length=500,
                    ),
                ),
                ("link_url", models.URLField(blank=True, default="", max_length=500)),
                ("link_text", models.CharField(blank=True, default="", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "hero banner",
                "verbose_name_plural": "hero banners",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="HomepageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("custom_design", "Custom Design (Coming Soon)"),
                            ("featured_collections", "Featured Collections"),
                            ("featured_products", "Featured Products"),
                            ("best_sellers", "Best Sellers"),
                            ("new_arrivals", "New Arrivals"),
                            ("about", "About Brand"),
                            ("newsletter", "Newsletter"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.TextField(blank=True, default="")),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Rich text content for sections like About.",
                    ),
                ),
                ("image_url", models.URLField(blank=True, default="", max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "homepage section",
                "verbose_name_plural": "homepage sections",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("brand_name", models.CharField(default="CustomCollection", max_length=100)),
                (
                    "brand_tagline",
                    models.CharField(blank=True, default="Premium Clothing Brand", max_length=200),
                ),
                (
                    "brand_description",
                    models.TextField(
                        blank=True,
                        default="Discover premium T-shirts crafted for those who appreciate quality and style.",
                    ),
                ),
                ("logo_url", models.URLField(blank=True, default="", max_length=500)),
                ("favicon_url", models.URLField(blank=True, default="", max_length=500)),
                ("contact_email", models.EmailField(blank=True, default="", max_length=254)),
                ("contact_phone", models.CharField(blank=True, default="", max_length=20)),
                ("address", models.TextField(blank=True, default="")),
                ("instagram_url", models.URLField(blank=True, default="", max_length=500)),
                ("twitter_url", models.URLField(blank=True, default="", max_length=500)),
                ("facebook_url", models.URLField(blank=True, default="", max_length=500)),
                ("youtube_url", models.URLField(blank=True, default="", max_length=500)),
                ("footer_text", models.TextField(blank=True, default="")),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        default="CustomCollection — Premium Clothing Brand",
                        max_length=160,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        default="Shop premium T-shirts at CustomCollection. Quality designs, crafted just for you.",
                        max_length=320,
                    ),
                ),
            ],
            options={
                "verbose_name": "site configuration",
                "verbose_name_plural": "site configuration",
            },
        ),
    ]
