# Generated by Django 5.1.15 on 2026-09-30 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
        ("collections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=25)),
                ("subject", models.CharField(blank=True, default="", max_length=200)),
                ("message", models.TextField()),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="Mark as read once reviewed by admin."
                    ),
                ),
            ],
            options={
                "verbose_name": "contact message",
                "verbose_name_plural": "contact messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="announcementbar",
            options={
                "ordering": ["sort_order", "-created_at"],
                "verbose_name": "announcement",
                "verbose_name_plural": "announcements",
            },
        ),
        migrations.AlterModelOptions(
            name="homepagesection",
            options={
                "ordering": ["sort_order", "-created_at"],
                "verbose_name": "homepage section",
                "verbose_name_plural": "homepage sections",
            },
        ),
        migrations.RemoveField(
            model_name="homepagesection",
            name="content",
        ),
        migrations.RemoveField(
            model_name="homepagesection",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="homepagesection",
            name="section_type",
        ),
        migrations.AddField(
            model_name="announcementbar",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display priority (lower numbers appear first)."
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="collection",
            field=models.ForeignKey(
                help_text="Select a collection to display in this homepage section.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homepage_sections",
                to="collections.collection",
            ),
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Toggle to show or hide this section on the homepage."
            ),
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers appear first on the homepage."
            ),
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="subtitle",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional subtitle or tagline displayed above the section title.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Custom title. If left blank, defaults to the collection name.",
                max_length=200,
            ),
        ),
    ]
