# Generated by Django 5.1.15 on 2026-09-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_contactmessage_alter_announcementbar_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="herobanner",
            name="show_content",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide title, subtitle, and CTA button, and keep the original clean image without dark shading.",
                verbose_name="Show Title & Subtitle on Banner",
            ),
        ),
        migrations.AlterField(
            model_name="herobanner",
            name="title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
