# Generated by Django 5.1.15 on 2026-10-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_herobanner_show_content_alter_herobanner_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "newsletter subscriber",
                "verbose_name_plural": "newsletter subscribers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="register_popup_bg_image",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Background image URL for the registration popup modal.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="register_popup_btn_text",
            field=models.CharField(
                blank=True,
                default="CREATE AN ACCOUNT",
                help_text="Button text redirecting user to the register page.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="register_popup_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Show first-visit registration reminder popup to unauthenticated visitors.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="register_popup_subtitle",
            field=models.CharField(
                blank=True,
                default="Sign up now to get early access to drops, exclusive collections, and member-only discounts.",
                help_text="Subtext or offer details shown on the popup.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="register_popup_title",
            field=models.CharField(
                blank=True,
                default="JOIN THE CLUB & GET 10% OFF",
                help_text="Catchy headline for the first-visit registration prompt.",
                max_length=200,
            ),
        ),
    ]
