# Generated by Django 5.1.15 on 2026-07-05 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "flat_shipping_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=99.0,
                        help_text="Flat shipping charge in INR.",
                        max_digits=10,
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=999.0,
                        help_text="Orders above this amount get free shipping (in INR).",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "shipping configuration",
                "verbose_name_plural": "shipping configuration",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_number",
                    models.CharField(db_index=True, editable=False, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("printing", "Printing"),
                            ("packed", "Packed"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("returned", "Returned"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "shipping_address",
                    models.JSONField(
                        help_text="Snapshot of the shipping address at time of order."
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("shipping_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes (not visible to customer).",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("product_slug", models.CharField(max_length=220)),
                ("product_image_url", models.URLField(blank=True, default="", max_length=500)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("size", models.CharField(max_length=10)),
                ("color", models.CharField(max_length=50)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "order item",
                "verbose_name_plural": "order items",
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "courier",
                    models.CharField(
                        help_text="Courier service name (e.g., Delhivery, BlueDart).",
                        max_length=100,
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(help_text="Courier tracking number.", max_length=100),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the order was handed to the courier.",
                        null=True,
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, help_text="When the order was delivered.", null=True
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "shipment",
                "verbose_name_plural": "shipments",
            },
        ),
    ]
