# Generated by Django 5.1.15 on 2026-07-05 10:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("collections", "0001_initial"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "hex_code",
                    models.CharField(help_text="Hex color code, e.g. #000000", max_length=7),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order. Lower numbers appear first."
                    ),
                ),
            ],
            options={
                "verbose_name": "color",
                "verbose_name_plural": "colors",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=10, unique=True)),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order. Lower numbers appear first."
                    ),
                ),
            ],
            options={
                "verbose_name": "size",
                "verbose_name_plural": "sizes",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "description",
                    models.TextField(help_text="Full product description (supports Markdown)."),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Brief description for product cards.",
                        max_length=300,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="If set, shown as the sale price. Must be less than price.",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Show in Featured Products section.",
                    ),
                ),
                (
                    "is_best_seller",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Show in Best Sellers section."
                    ),
                ),
                (
                    "is_new_arrival",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Show in New Arrivals section."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "wash_care",
                    models.TextField(
                        blank=True, default="", help_text="Wash and care instructions."
                    ),
                ),
                (
                    "shipping_info",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Shipping details specific to this product.",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, default="", max_length=160)),
                ("meta_description", models.TextField(blank=True, default="", max_length=320)),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="collections.collection"
                    ),
                ),
                (
                    "colors",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="products.color"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="products", to="tags.tag"),
                ),
                (
                    "sizes",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="products.size"
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image_url",
                    models.URLField(help_text="Cloudinary URL for the image.", max_length=500),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Alt text for accessibility.",
                        max_length=200,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary image shown on product cards."
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order in the gallery."
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product image",
                "verbose_name_plural": "product images",
                "ordering": ["-is_primary", "sort_order"],
            },
        ),
    ]
